#line 2 "lex.yy.c"

#line 4 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 51
#define YY_END_OF_BUFFER 52
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[298] =
    {   0,
        0,    0,    0,    0,   52,   51,   49,   50,   51,   51,
       51,   41,   51,   44,   45,   39,   42,   46,   43,    5,
       40,    9,   47,   35,   33,   34,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,    2,   51,   49,   36,    0,
        8,    0,    4,    0,    9,   37,   32,   38,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   24,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,

       48,   48,   48,   48,   48,   48,   48,   48,   48,    2,
        3,    7,   23,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   25,   48,   48,   48,   48,   26,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   21,   48,   48,   48,   13,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   17,   48,   20,   48,   48,   48,
       48,   48,   48,   10,   48,   48,   18,   27,   16,   48,

       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   11,   15,   48,   48,   48,   48,   12,   22,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   19,
       48,   14,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,    1,   48,   48,   48,   48,   31,
       48,   48,   48,   48,   48,   48,    6,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   30,
       48,   48,   29,   48,   48,   28,    0

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    1,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,    1,   18,   19,
       20,   21,    1,    1,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
       32,   38,   39,   40,   41,   42,   43,   32,   32,   32,
        1,   44,    1,    1,   45,    1,   46,   47,   48,   49,

       50,   51,   52,   53,   54,   55,   56,   57,   58,   59,
       60,   61,   56,   62,   63,   64,   65,   66,   67,   56,
       56,   56,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[69] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    4,    1,    1,
        1,    1,    1,    1,    1,    1,    5,    1,    1,    1,
        6,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    4,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    6
    } ;

static yyconst flex_int16_t yy_base[305] =
    {   0,
        0,    0,   66,   67,  725,  726,  722,  726,  703,  717,
      718,  726,    0,  726,  726,  726,  726,  726,  726,  726,
      726,  703,  726,  699,  698,  694,   54,   55,   56,   57,
       60,   58,   61,   64,   80,   66,   91,   93,   95,   98,
       97,   62,   96,  101,  103,  105,  113,  107,  106,  114,
      122,  128,  145,  130,  132,    0,  707,  707,  726,  693,
      726,  693,  726,  679,  669,  726,  726,  726,    0,  151,
      157,  163,  164,  153,  162,  170,  178,  166,  152,  182,
      183,  187,  193,  195,  196,  201,  199,  207,  219,  222,
      202,  212,  214,  218,  225,  226,  233,  236,  237,  239,

      244,  245,  249,  252,  251,  255,  257,  271,  274,    0,
      726,  726,  256,  282,  292,  275,  301,  309,  295,  297,
      298,  315,  305,  311,  318,  327,  321,  328,  331,  332,
      334,  336,  335,  338,  340,  344,  348,  350,  342,  351,
      353,  367,  358,  369,  361,  374,  380,  384,  387,  388,
      390,  392,  398,  399,  409,  406,  411,  410,  414,  430,
      436,  423,  440,  441,  443,  444,  448,  450,  453,  454,
      456,  461,  460,  462,  463,  466,  479,  467,  465,  483,
      485,  487,  499,  651,  492,  517,  506,  519,  516,  521,
      523,  524,  529,  531,  533,  535,  536,  538,  540,  626,

      541,  542,  543,  550,  553,  555,  560,  565,  567,  572,
      661,  573,  577,  580,  585,  584,  591,  652,  587,  592,
      635,  594,  596,  598,  599,  602,  626,  639,  648,  603,
      617,  610,  641,  611,  620,  621,  611,  614,  646,  636,
      618,  629,  617,  606,  726,  625,  600,  620,  618,  632,
      630,  627,  589,  587,  585,  546,    0,  567,  541,  537,
      521,  459,  452,  465,  471,  452,  430,  441,  424,  445,
      414,  408,  356,  372,  346,  360,  331,  252,  234,  215,
      220,  232,  228,  216,  164,  163,  142,  125,  108,    0,
       69,   68,    0,   92,   23,    0,  726,  688,  694,  700,

      706,   75,  712,   71
    } ;

static yyconst flex_int16_t yy_def[305] =
    {   0,
      297,    1,  298,  298,  297,  297,  297,  297,  297,  299,
      300,  297,  301,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  303,  297,  297,  297,  299,
      297,  300,  297,  297,  297,  297,  297,  297,  304,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,

      302,  302,  302,  302,  302,  302,  302,  302,  302,  303,
      297,  297,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  304,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  304,

      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      304,  302,  302,  302,  302,  302,  302,  304,  302,  302,
      304,  302,  302,  302,  302,  302,  304,  304,  304,  302,
      302,  302,  304,  304,  304,  302,  302,  304,  304,  304,
      302,  304,  304,  304,  297,  302,  304,  304,  304,  302,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,    0,  297,  297,  297,

      297,  297,  297,  297
    } ;

static yyconst flex_int16_t yy_nxt[795] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   30,   31,   32,   30,   33,
       30,   30,   30,   34,   35,   36,   37,   30,   38,   39,
       40,   30,   41,    6,    6,   42,   43,   44,   30,   30,
       45,   46,   30,   47,   30,   30,   30,   48,   49,   50,
       51,   30,   52,   53,   54,   30,   55,    6,    6,    6,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   70,
       69,  296,   69,   78,   73,   81,   57,   57,   71,   82,
       72,   74,   76,   75,   79,   80,   69,   77,   69,   69,

       69,   69,   69,   84,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   83,   88,   69,   86,   69,
       91,   69,   69,   69,   69,   90,  296,  295,   85,   69,
       69,  293,   87,    6,    6,   69,   89,   69,   69,   69,
       69,   69,   69,  294,   69,   69,   69,   69,   69,   69,
       69,   69,  101,   93,   98,   92,  102,   69,   69,   96,
       94,   69,   95,  293,   97,  103,   69,   69,   69,   69,
       99,  100,   69,   69,   69,   84,   69,  105,   69,   69,
       69,  113,   69,  104,  109,  115,   69,  117,  121,   69,
      107,  106,  108,  116,   69,   69,   69,   69,   69,   69,

      120,   69,  114,   69,  290,  118,   69,   69,   69,   69,
       69,   69,   69,  119,   69,   69,  292,   69,   69,  123,
      291,  122,   69,   69,  124,  126,   69,   69,   69,  129,
       69,   69,  125,  127,   69,   69,  128,   69,   69,   69,
       69,   69,   69,   69,  130,   69,   69,  132,  131,   69,
      113,   69,   69,   69,  290,   69,   69,  289,   69,  134,
       69,   69,   69,   69,  288,   69,   69,   69,   69,   69,
       69,   69,   69,   69,  136,  133,  287,   69,  286,  285,
       69,   69,  135,   69,  284,  137,  141,   69,   69,   69,
       69,   69,  138,   69,  139,   69,   69,  140,   69,   69,

       69,   69,  142,  148,  143,  145,  144,  146,   69,  153,
      151,   69,  125,   69,   69,   69,  147,   69,   69,   69,
      130,   69,  154,  150,  149,   69,   69,   69,  156,  152,
      155,   69,  157,  158,   69,  160,   69,   69,  161,   69,
      159,   69,   69,   69,   69,   69,  163,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,  164,   69,   69,
       69,  162,   69,  165,   69,   69,   69,   69,  166,   69,
      283,   69,   69,  167,   69,   69,   69,   69,   69,   69,
       69,  282,   69,   69,   69,   69,   69,  168,   69,  170,
       69,  281,   69,  171,   69,   69,   69,   69,  169,  152,

       69,  172,   69,   69,   69,   69,   69,  156,   69,  174,
      173,   69,  176,   69,   69,   69,  175,  280,   69,  178,
      177,  279,   69,  179,   69,   69,   69,   69,   69,  278,
       69,   69,   69,  180,  184,  277,   69,  185,  186,   69,
      181,  190,   69,   69,  188,  182,   69,  189,  187,  183,
       69,  191,   69,   69,   69,   69,   69,   69,   69,   69,
       69,  193,  194,  195,   69,  192,   69,   69,  197,   69,
       69,  198,   69,  199,   69,  196,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,  276,   69,   69,  275,
      274,  273,   69,  272,  200,   69,  271,   69,   69,   69,

       69,   69,  270,   69,   69,   69,   69,   69,   69,   69,
       69,   69,  209,  269,  205,   69,  185,  201,  202,  187,
      268,  203,   69,   69,  206,  207,  204,   69,  208,   69,
      194,   69,   69,   69,  197,   69,   69,   69,  198,   69,
       69,  210,  212,   69,  213,   69,  215,   69,  199,   69,
       69,   69,   69,  217,   69,  214,   69,   69,   69,   69,
       69,   69,  220,   69,  216,   69,   69,   69,   69,   69,
      267,   69,  219,  218,  266,   69,   69,   69,  265,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
      222,  213,  264,   69,   69,  263,   69,   69,  223,   69,

       69,   69,  224,   69,   69,  231,  214,   69,   69,  227,
       69,   69,   69,  226,   69,   69,   69,  229,   69,   69,
      225,   69,  230,  220,   69,  232,   69,   69,   69,   69,
      219,   69,  262,   69,   69,   69,   69,   69,  235,  245,
       69,   69,   69,   69,  237,  236,   69,   69,   69,  241,
      261,  257,  260,  259,   69,   69,  250,  258,  257,  230,
      232,   69,  251,  256,  254,   69,  253,  246,  252,  255,
      249,  248,  247,  244,  243,  242,   69,  240,  239,  238,
      234,  233,  228,  221,  211,   65,  112,  250,   56,   56,
       56,   56,   56,   56,   60,   63,   60,   61,   60,   60,

       62,   62,   62,   62,   62,   62,   64,   64,   58,  111,
       64,   64,  110,   68,  110,  110,  110,   67,   66,   65,
       63,   61,   59,   58,  297,    5,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297

    } ;

static yyconst flex_int16_t yy_chk[795] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    4,
       27,   28,   29,   30,   32,  304,   31,   33,   42,  302,
       34,  295,   36,   32,   29,   34,    3,    4,   27,   34,
       28,   29,   31,   29,   33,   33,   35,   31,   27,   28,

       29,   30,   32,   36,   31,   33,   42,   37,   34,   38,
       36,   39,   43,   41,   40,   35,   39,   44,   38,   45,
       42,   46,   49,   48,   35,   41,  294,  292,   37,   47,
       50,  291,   38,    3,    4,   37,   40,   38,   51,   39,
       43,   41,   40,  289,   52,   44,   54,   45,   55,   46,
       49,   48,   48,   44,   46,   43,   48,   47,   50,   45,
       44,   53,   44,  288,   45,   49,   51,   70,   79,   74,
       47,   47,   52,   71,   54,   50,   55,   52,   75,   72,
       73,   71,   78,   51,   55,   73,   76,   75,   79,   53,
       53,   52,   54,   74,   77,   70,   79,   74,   80,   81,

       78,   71,   72,   82,  287,   76,   75,   72,   73,   83,
       78,   84,   85,   77,   76,   87,  286,   86,   91,   81,
      285,   80,   77,   88,   82,   85,   80,   81,   92,   88,
       93,   82,   83,   86,   94,   89,   87,   83,   90,   84,
       85,   95,   96,   87,   89,   86,   91,   90,   89,   97,
       91,   88,   98,   99,  284,  100,   92,  283,   93,   93,
      101,  102,   94,   89,  282,  103,   90,  105,  104,   95,
       96,  106,  113,  107,   95,   92,  281,   97,  280,  279,
       98,   99,   94,  100,  278,   96,  100,  108,  101,  102,
      109,  116,   97,  103,   98,  105,  104,   99,  114,  106,

      113,  107,  100,  107,  101,  104,  102,  105,  115,  116,
      114,  119,  103,  120,  121,  108,  106,  117,  109,  116,
      108,  123,  117,  109,  108,  118,  114,  124,  119,  115,
      118,  122,  120,  121,  125,  123,  115,  127,  124,  119,
      122,  120,  121,  126,  128,  117,  127,  129,  130,  123,
      131,  133,  132,  118,  134,  124,  135,  128,  139,  122,
      136,  126,  125,  129,  137,  127,  138,  140,  131,  141,
      277,  126,  128,  132,  143,  129,  130,  145,  131,  133,
      132,  276,  134,  142,  135,  144,  139,  133,  136,  136,
      146,  275,  137,  137,  138,  140,  147,  141,  135,  134,

      148,  139,  143,  149,  150,  145,  151,  138,  152,  141,
      140,  142,  143,  144,  153,  154,  142,  274,  146,  145,
      144,  273,  156,  146,  147,  155,  158,  157,  148,  272,
      159,  149,  150,  147,  151,  271,  152,  153,  154,  162,
      148,  159,  153,  154,  157,  149,  160,  158,  155,  150,
      156,  159,  161,  155,  158,  157,  163,  164,  159,  165,
      166,  161,  162,  163,  167,  160,  168,  162,  165,  169,
      170,  166,  171,  167,  160,  164,  173,  172,  174,  175,
      161,  179,  176,  178,  163,  164,  270,  165,  166,  269,
      268,  267,  167,  266,  168,  177,  265,  169,  170,  180,

      171,  181,  264,  182,  173,  172,  174,  175,  185,  179,
      176,  178,  179,  263,  175,  183,  169,  170,  172,  171,
      262,  173,  187,  177,  175,  176,  174,  180,  177,  181,
      178,  182,  189,  186,  181,  188,  185,  190,  182,  191,
      192,  180,  186,  183,  188,  193,  190,  194,  183,  195,
      187,  196,  197,  192,  198,  189,  199,  201,  202,  203,
      189,  186,  196,  188,  191,  190,  204,  191,  192,  205,
      261,  206,  195,  193,  260,  194,  207,  195,  259,  196,
      197,  208,  198,  209,  199,  201,  202,  203,  210,  212,
      201,  202,  258,  213,  204,  256,  214,  205,  204,  206,

      216,  215,  205,  219,  207,  216,  203,  217,  220,  208,
      222,  209,  223,  207,  224,  225,  210,  212,  226,  230,
      206,  213,  215,  210,  214,  217,  232,  237,  216,  215,
      209,  219,  255,  231,  241,  217,  220,  236,  222,  236,
      223,  246,  224,  225,  225,  223,  226,  230,  250,  231,
      254,  253,  252,  251,  232,  237,  241,  249,  248,  224,
      226,  231,  241,  247,  244,  236,  243,  237,  242,  246,
      240,  239,  238,  235,  234,  233,  250,  229,  228,  227,
      221,  218,  211,  200,  184,   65,   64,  246,  298,  298,
      298,  298,  298,  298,  299,   62,  299,   60,  299,  299,

      300,  300,  300,  300,  300,  300,  301,  301,   58,   57,
      301,  301,  303,   26,  303,  303,  303,   25,   24,   22,
       11,   10,    9,    7,    5,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "biosql.l"
#line 2 "biosql.l"
	#include<math.h>
	#include<malloc.h>
	#include<string>
	#include "biosql.h"
	#include <iostream>
	
	using namespace std;
	int lineNo;

	int errorNo;
	int errors=0;
	int line=1;
	int old_line;

	extern "C"{
		int yylex(void);
	}

#line 756 "lex.yy.c"

#define INITIAL 0
#define incl 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 55 "biosql.l"

#line 946 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 298 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 726 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 56 "biosql.l"
{BEGIN(incl); old_line=line;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 57 "biosql.l"
{
	//cout << yytext << endl;
	//cout << YY_BUF_SIZE << endl;
	
	yyin = fopen( yytext, "r" );
	if(yyin==NULL){
		cout << "FILE NOT FOUND " << yytext <<endl;
		exit(2);
	}
	yypush_buffer_state(yy_create_buffer(yyin,YY_BUF_SIZE ));	
	BEGIN(INITIAL);
	

}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 71 "biosql.l"
{
	//cout << "ending include" << endl;
	line=old_line+1;
	BEGIN(INITIAL);
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(incl):
#line 76 "biosql.l"
{
	yypop_buffer_state();
	if ( !YY_CURRENT_BUFFER )
	{
		//cout << "yyterminating" << endl;
		yyterminate();


	}
	BEGIN(incl);
	

}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 90 "biosql.l"
{lineNo=line++; /*printf("comment line: %s\n",yytext);*/}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 92 "biosql.l"
{
	lineNo=line;
	
	yylval.str=new string(yytext);
	return DOT;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 98 "biosql.l"
{
	lineNo=line;
	
	yylval.str=new string(yytext);
	return BOTH_MATES;

}
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 105 "biosql.l"
{
	lineNo=line;
	
	yylval.str=new string(yytext);
	return CONST_CHAR;
	//printf("constChar: %s\n",yytext);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 113 "biosql.l"
{
	lineNo=line;
	
	yylval.str=new string(yytext);
	return CONST_STRING;

	//printf("constString: %s\n",yytext);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 122 "biosql.l"
{
	lineNo=line;
	
	yylval.str=new string(yytext);
	return NUMBER;

	//printf("number: %s\n",yytext);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 130 "biosql.l"
{
	lineNo=line;
	yylval.str=new string(yytext);
	return PRINT;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 136 "biosql.l"
{
	lineNo=line;//printf("where\n");
	
	yylval.str=new string(yytext);
	return GENOME;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 143 "biosql.l"
{
	lineNo=line;//printf("select\n");
	
	yylval.str=new string(yytext);
	return SELECT;

}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 151 "biosql.l"
{
	lineNo=line;//printf("where\n");
	
	yylval.str=new string(yytext);
	return FROM;

}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 158 "biosql.l"
{
	lineNo=line;//printf("where\n");
	
	yylval.str=new string(yytext);
	return MAPJOIN;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 165 "biosql.l"
{
	lineNo=line;//printf("where\n");
	
	yylval.str=new string(yytext);
	return IMPORT;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 174 "biosql.l"
{
	lineNo=line;//printf("where\n");
	
	yylval.str=new string(yytext);
	return WHERE;

}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 182 "biosql.l"
{
	lineNo=line;//printf("count\n");
	
	yylval.str=new string(yytext);
	return COUNT;

}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 190 "biosql.l"
{
	lineNo=line;//printf("count\n");
	
	yylval.str=new string(yytext);
	return TABLE;

}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 198 "biosql.l"
{
	lineNo=line;//printf("count\n");
	
	yylval.str=new string(yytext);
	return INTEGER;

}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 206 "biosql.l"
{
	lineNo=line;//printf("count\n");
	
	yylval.str=new string(yytext);
	return FLOAT;

}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 214 "biosql.l"
{
	lineNo=line;//printf("count\n");
	
	yylval.str=new string(yytext);
	return CHAR;

}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 222 "biosql.l"
{
	lineNo=line;//printf("count\n");
	
	yylval.str=new string(yytext);
	return STRING_TYPE;

}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 229 "biosql.l"
{
	lineNo=line;//printf("and\n");
	
	yylval.str=new string(yytext);
	return AND;

}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 237 "biosql.l"
{
	lineNo=line;//printf("or\n");
	
	yylval.str=new string(yytext);
	return OR;

}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 245 "biosql.l"
{
	lineNo=line;//printf("or\n");
	
	yylval.str=new string(yytext);
	return NOT;

}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 253 "biosql.l"
{
	lineNo=line;//printf("or\n");
	
	yylval.str=new string(yytext);
	return USE;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 260 "biosql.l"
{
	lineNo=line;//printf("or\n");
	
	yylval.str=new string(yytext);
	return USING;

}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 267 "biosql.l"
{
	lineNo=line;//printf("or\n");
	
	yylval.str=new string(yytext);
	return INTERVAL_CREATION;

}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 275 "biosql.l"
{
	lineNo=line;//printf("or\n");
	yylval.str=new string(yytext);
	return CREATE_INTERVALS;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 281 "biosql.l"
{
	lineNo=line;//printf("or\n");
	yylval.str=new string(yytext);
	return MERGE_INTERVALS;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 288 "biosql.l"
{
	lineNo=line;//printf("or\n");
	
	yylval.str=new string(yytext);
	return INTERVALS;

}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 296 "biosql.l"
{
	lineNo=line;//printf("equality\n");/*return TK_EQUAL*/
	
	yylval.str=new string(yytext);
	return EQUAL;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 303 "biosql.l"
{lineNo=line;//printf("assignment\n");/*return TK_ASSIGN*/
	
	yylval.str=new string(yytext);
	return ASSIGN;
	
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 310 "biosql.l"
{
	lineNo=line;//printf("greater\n");/*return TK_GREATER*/
	
	yylval.str=new string(yytext);
	return GREATER;

}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 318 "biosql.l"
{
	lineNo=line;//printf("less\n");/*return TK_LESS*/
	
	yylval.str=new string(yytext);
	return LESS;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 325 "biosql.l"
{
	lineNo=line;//printf("neq\n");/*return TK_NOT_EQUAL*/
	
	yylval.str=new string(yytext);
	return NOT_EQUAL;
	
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 333 "biosql.l"
{
	lineNo=line;//printf("leq\n");/*return TK_LESS_EQUAL*/
	
	yylval.str=new string(yytext);
	return LESS_EQUAL;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 340 "biosql.l"
{
	lineNo=line;//printf("geq\n");/*return TK_GREATER_EQUAL*/
	
	yylval.str=new string(yytext);
	return GREATER_EQUAL;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 347 "biosql.l"
{
	lineNo=line;//printf("star\n");/*return TK_MUL*/
	
	yylval.str=new string(yytext);
	return STAR;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 354 "biosql.l"
{
	lineNo=line;//printf("div\n");/*return TK_DIV*/
	
	yylval.str=new string(yytext);
	return DIV;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 361 "biosql.l"
{
	lineNo=line;//printf("mod\n");/*return TK_MOD*/
	
	yylval.str=new string(yytext);
	return MOD;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 368 "biosql.l"
{
	lineNo=line;//printf("plus\n");/*return TK_PLUS*/
	
	yylval.str=new string(yytext);
	return PLUS;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 375 "biosql.l"
{
	lineNo=line;//printf("minus\n");/*return TK_MINUS*/
	
	yylval.str=new string(yytext);
	return MINUS;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 382 "biosql.l"
{
	lineNo=line;//printf("lparen\n");/*return TK_LEFT_BRACKET*/
	
	yylval.str=new string(yytext);
	return LPAREN;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 389 "biosql.l"
{
	lineNo=line;//printf("rparen\n");/*return TK_RIGHT_BRACKET*/
	
	yylval.str=new string(yytext);
	return RPAREN;

}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 397 "biosql.l"
{
	lineNo=line;//printf("comma\n");/*return TK_COMMA*/
	
	yylval.str=new string(yytext);
	return COMMA;
	
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 405 "biosql.l"
{
	lineNo=line;//printf("comma\n");/*return TK_COMMA*/
	
	yylval.str=new string(yytext);
	return SEMICOLON;
	
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 413 "biosql.l"
{
	lineNo=line;//printf("name: %s\n",yytext);
	
	yylval.str=new string(yytext);
	return ID;

}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 420 "biosql.l"
/*eat whitespace*/
	YY_BREAK
case 50:
/* rule 50 can match eol */
YY_RULE_SETUP
#line 421 "biosql.l"
{line++;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 423 "biosql.l"
ECHO;
	YY_BREAK
#line 1566 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 68);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 298 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 68;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 298 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 297);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 423 "biosql.l"



//main(){yylex();}

